extern void ota_init();
extern void simple_ota_example_task(void *pvParameters);
extern void i2c_init();
extern void bmi_spi_init();
extern void poll_sensor();
extern void udp_create_socket();
extern void led_run(void *pvParameters);
extern void udp_server_task(void *pvParameters);
extern esp_err_t wifi_init_sta(void);
extern void bmi_send_sensor_data_task(void *pvParameters);